name: STAC Validator

on: workflow_dispatch

jobs:
  validate:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Install stactools
      run: |
        pip install stactools~=0.2

    - name: Validate STAC
      shell: bash
      run: |
        stac validate catalog.json
